# Generated by Django 5.1.5 on 2025-01-26 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_bac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='authen.bac')),
            ],
        ),
    ]
