# Generated by Django 5.1.5 on 2025-02-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_cour'),
    ]

    operations = [
        migrations.AddField(
            model_name='bac',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bac_images/'),
        ),
    ]
