# Generated by Django 5.1.5 on 2025-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_bac_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matiere_images/'),
        ),
    ]
